### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by dmcg89** [Genji-MS/Madlibs#1]
https://github.com/Genji-MS/Madlibs/blob/482bac7db9fbcbd639e588747c0f180a5d76d73e/script.py#L38

Overall, very nice implementation.  Here is a newer python3 formatted print that I enjoy, I hope you do too! https://cito.github.io/blog/f-strings/

**Comment by Genji-MS** [comment]
Sweet, thanks for that. I suppose I can agree with the easy readability with it written in this new form.
- Cheers
